//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public decimal id { get; set; }
        public decimal klass_seminar_id { get; set; }
        public decimal team_id { get; set; }
        public byte team_order { get; set; }
        public byte is_present { get; set; }
        public string report_name { get; set; }
        public string report_url { get; set; }
        public string ppt_name { get; set; }
        public string ppt_url { get; set; }
    }
}
