//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_member_limit_strategy
    {
        public decimal id { get; set; }
        public byte course_id { get; set; }
        public Nullable<byte> min_member { get; set; }
        public Nullable<byte> max_member { get; set; }
    }
}
