//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public decimal id { get; set; }
        public decimal teacher_id { get; set; }
        public string course_name { get; set; }
        public string introduction { get; set; }
        public byte presentation_percentage { get; set; }
        public byte question_percentage { get; set; }
        public byte report_percentage { get; set; }
        public System.DateTime team_start_time { get; set; }
        public System.DateTime team_end_time { get; set; }
        public Nullable<decimal> team_main_course_id { get; set; }
        public Nullable<decimal> seminar_main_course_id { get; set; }
    }
}
