//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class round
    {
        public decimal id { get; set; }
        public decimal course_id { get; set; }
        public byte round_serial { get; set; }
        public byte presentation_score_method { get; set; }
        public byte report_score_method { get; set; }
        public byte question_score_method { get; set; }
    }
}
