//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class round_score
    {
        public decimal round_id { get; set; }
        public decimal team_id { get; set; }
        public Nullable<decimal> total_score { get; set; }
        public Nullable<decimal> presentation_score { get; set; }
        public Nullable<decimal> question_score { get; set; }
        public Nullable<decimal> report_score { get; set; }
    }
}
