//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seminar
    {
        public decimal id { get; set; }
        public decimal course_id { get; set; }
        public decimal round_id { get; set; }
        public string seminar_name { get; set; }
        public string introduction { get; set; }
        public byte max_team { get; set; }
        public byte is_visible { get; set; }
        public byte seminar_serial { get; set; }
        public Nullable<System.DateTime> enroll_start_time { get; set; }
        public Nullable<System.DateTime> enroll_end_time { get; set; }
    }
}
