//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class share_seminar_application
    {
        public decimal id { get; set; }
        public decimal main_course_id { get; set; }
        public decimal sub_course_id { get; set; }
        public decimal sub_course_teacher_id { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
