//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySQLContext : DbContext
    {
        public MySQLContext()
            : base("name=MySQLContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<attendance> attendance { get; set; }
        public virtual DbSet<conflict_course_strategy> conflict_course_strategy { get; set; }
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<course_member_limit_strategy> course_member_limit_strategy { get; set; }
        public virtual DbSet<klass> klass { get; set; }
        public virtual DbSet<klass_round> klass_round { get; set; }
        public virtual DbSet<klass_seminar> klass_seminar { get; set; }
        public virtual DbSet<klass_student> klass_student { get; set; }
        public virtual DbSet<member_limit_strategy> member_limit_strategy { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<round> round { get; set; }
        public virtual DbSet<round_score> round_score { get; set; }
        public virtual DbSet<seminar> seminar { get; set; }
        public virtual DbSet<seminar_score> seminar_score { get; set; }
        public virtual DbSet<share_seminar_application> share_seminar_application { get; set; }
        public virtual DbSet<share_team_application> share_team_application { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<team> team { get; set; }
        public virtual DbSet<team_and_strategy> team_and_strategy { get; set; }
        public virtual DbSet<team_or_strategy> team_or_strategy { get; set; }
        public virtual DbSet<team_strategy> team_strategy { get; set; }
        public virtual DbSet<team_valid_application> team_valid_application { get; set; }
    }
}
