//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_valid_application
    {
        public decimal id { get; set; }
        public decimal team_id { get; set; }
        public decimal teacher_id { get; set; }
        public string reason { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
