//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_and_strategy
    {
        public decimal id { get; set; }
        public string strategy_1_name { get; set; }
        public decimal strategy_1_id { get; set; }
        public string strategy_2_name { get; set; }
        public decimal strategy_2_id { get; set; }
    }
}
